#!/bin/bash
#
# Program: get curl status and speed
# Author: shazi
URL=$1
 
curl -A 1231 -o /dev/null -s -w\
"
HTTP status code:       %{http_code}\n\
DNS resolve:            %{time_namelookup}\n\
connect to server:      %{time_connect}\n\
handshake SSL server:   %{time_appconnect}\n\
Server first respon:    %{time_starttransfer}\n\
header size(bytes):     %{size_header}\n\
request size(bytes):    %{size_request}\n\
------------------------------------\n\
Total time:             %{time_total} sec\n
" \
"${URL}"
