#!/bin/sh
# 
# Program: Optimize image file
# Author: shazi
# github: https://github.com/shazi7804
trap 'stop' SIGUSR1 SIGINT SIGHUP SIGQUIT SIGTERM SIGSTOP

stop() {
	exit 0
}

helpmsg() {
    echo "Usage: $0 [DIR] [OPTION]"
    echo ""
    echo "OPTION:"
    echo "  -jpg    use jpegoptim optimize jpg/jpeg."
    echo "  -png    use optipng optimize png. (default level:o7)"
    echo ""
    echo "Example:"
    echo "$0 /image -jpg -png"
    echo ""
}

jpg_conv() {
    # Optimize JPEG/JPG images
    if [[ ! -x /usr/bin/jpegoptim ]]; then
		echo "Check jpegoptim install ... no"
		read -p "Do you want to install jpegoptim? [y/n]:" jpegoptim_ask
		if [[ $jpegoptim_ask = +(y|Y) ]]; then
			yum install -y jpegoptim
			echo "jpegoptim install finish."
		fi
	fi
    EXTENSIONS=jpe?g
    find "$DIR" -regextype posix-egrep -regex ".*\.(${EXTENSIONS})\$" -type f | xargs jpegoptim --strip-all
}

png_conv() {
    # Optimize PNG images
    if [[ ! -x /usr/bin/optipng ]]; then
		echo "Check optipng install ... no"
		read -p "Do you want to install optipng? [y/n]:" optipng_ask
		if [[ $optipng_ask = +(y|Y) ]]; then
			yum install -y optipng
			echo "optipng install finish."
		fi
	fi
    find "$DIR" -name '*.png' | xargs optipng -nc -nb -o7 -full
}

convert=()
DIR="$1"
shift

if [[ $# -ge 1 ]]; then
	for opt in $1
	do
		case $opt in
			-jpg)
				convert+=('jpg');;
			-png)
				convert+=('png');;
			-h|--help|-help|*)
				helpmsg
				exit;;
		esac
	done
else
    helpmsg
    exit 0
fi

for (( i = 0; i < ${#convert[@]}; i++ )); do
	if [[ "jpg" == ${convert[i]} ]]; then
		jpg_conv
	elif [[ "png" == ${convert[i]} ]]; then
		png_conv
	fi
done
