#!/bin/bash
#
# Program: ts video more download and merge
# Author: shazi
URL=$1
shift
#wget ${URL}/65189_500{0..165}.ts &
wget ${URL}/$@ &
wait
echo $@ | tr " " "\n" > tslist
while read line; do cat $line >> combined.ts; done < tslist


